# Generated by Django 4.0.4 on 2022-05-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_studentdetails_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='regNo',
            field=models.IntegerField(unique=True),
        ),
    ]
