# Generated by Django 4.0.4 on 2022-05-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_studentdetails_regno'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_id', models.CharField(max_length=10, unique=True)),
                ('d_name', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=40)),
                ('experience', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
