# Generated by Django 4.0.5 on 2022-06-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_doctordetails_alter_studentdetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='d_id',
            field=models.IntegerField(unique=True),
        ),
    ]
