# Generated by Django 4.0.4 on 2022-06-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_doctordetails_d_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
