# Generated by Django 4.0.5 on 2022-06-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_studentdetails_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='avaliable',
            field=models.CharField(default='avaliable', max_length=15),
        ),
    ]
