# Generated by Django 4.0.4 on 2022-06-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_studentdetails_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='availableDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dName', models.CharField(max_length=20)),
                ('sName', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'home_doctordetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='specialist',
            fields=[
                ('sName', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'specialization',
            },
        ),
        migrations.RemoveField(
            model_name='doctordetails',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctordetails',
            name='d_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='regNo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
