# Generated by Django 4.0.5 on 2022-06-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_doctordetails_avaliable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordetails',
            name='avaliable',
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='available',
            field=models.CharField(default='Available', max_length=15),
        ),
    ]
