# Generated by Django 4.0.6 on 2022-08-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_doctordetails_avaliable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='report',
            field=models.CharField(default='', max_length=20),
        ),
    ]
