# Generated by Django 4.0.4 on 2022-06-09 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_doctordetails_avaliable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('appDate', models.DateField(blank=True, null=True)),
                ('timeSlot', models.CharField(max_length=20)),
                ('tokenNo', models.AutoField(primary_key=True, serialize=False)),
                ('problem', models.CharField(max_length=200)),
                ('deptName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deptName', to='home.doctordetails')),
                ('docName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docName', to='home.doctordetails')),
                ('regNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.studentdetails')),
            ],
        ),
    ]
