# Generated by Django 4.0.4 on 2022-06-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_appointmentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='deptName',
        ),
        migrations.AlterModelTable(
            name='doctordetails',
            table='home_DoctorDetails',
        ),
    ]
