# Generated by Django 4.0.4 on 2022-06-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_appointmentdetails_deptname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('regNo', models.IntegerField()),
                ('docNameSpec', models.CharField(max_length=200)),
                ('appDate', models.DateField()),
                ('timeSlot', models.CharField(max_length=20)),
                ('tokenNo', models.IntegerField(primary_key=True, serialize=False)),
                ('problem', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelTable(
            name='doctordetails',
            table=None,
        ),
        migrations.DeleteModel(
            name='AppointmentDetails',
        ),
    ]
